### ISSUE TITLE
Classification tags seem to be broken

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#100]
Clic Sargent has no tags in the app, but tags are populated in the CSV: http://app.sogive.org/#edit?charityId=clic-sargent-cancer-care-for-children
Children's Society has tags in the CSV, those are missing from the app, but instead the alternative name for the charity is treated as a tag: http://app.sogive.org/#charity?charityId=children-s-society

**Comment by roscoemcinerney** [comment]
Latest version correctly imports and displays tags. Charities can now also be searched by tag.
