### ISSUE TITLE
Extra info on impact units has not been uploaded from CSV

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#102]
We have a column in the spreadsheet labelled "Extra Info 1". We also have an equivalent field in the editor, which is entitled "description" (note that we have several other fields called description)

The content from Extra Info 1 doesn't appear to have been uploaded into the editor/app.
Examples of charities where I checked this:
http://app.sogive.org/#edit?charityId=oxfam ; Overall section
http://app.sogive.org/#edit?charityId=macmillan-cancer-support ; Overall section
http://app.sogive.org/#edit?charityId=red-cross ; Project - emergency response

**Comment by roscoemcinerney** [comment]
The upcoming patch places Extra Info 1 (and 2-6, if you decide to put those in) in the Description field on each output.
