### ISSUE TITLE
Accepts donations -- comments

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#104]
Whenever a charity has the answer "no" for "accepts donations", there is always a reason for it, which suggests that there should be a comment field for this. Especially since a user currently encounters a charity landing page which bluntly tells the user that they can't donate, and doesn't explain why -- given that we have gone to the trouble of finding out why, it seems only fair to share this info with the user.

**Comment by roscoemcinerney** [comment]
I've set up the importer to take values which are neither "Yes" nor simply "No" and add them as a note on the "no public donations" checkbox. The text of these notes isn't great for public consumption, but it displays on the charity pages as requested (most of these are marked not-ready so only editors can see them, anyway)
