### ISSUE TITLE
Confidence indicators currently all incorrect

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#105]
The confidence indicator seems to be set to high everywhere. I haven't found a case where the confidence indicator in the app agrees with the confidence level set in the spreadsheet (column BD in the spreadsheet)

Examples where the figures in the spreadsheet and the app disagree - pretty much anything. 
E.g. these ones are "low" in the spreadsheet, but "high" in the editor:
http://app.sogive.org/#edit?charityId=st-mungo-s
http://app.sogive.org/#edit?charityId=scope

These are medium in the spreadsheet but high in the editor:
http://app.sogive.org/#edit?charityId=voluntary-service-overseas-vso
http://app.sogive.org/#edit?charityId=restless-development

**Comment by roscoemcinerney** [comment]
The importer treats confidence levels (where they're present) correctly.

Note that there were a few charities in the spreadsheet with non-standard confidence levels. I've fixed all but one.

		Evidence action: Medium-High (Unchanged as I'm not the one to make this judgement call)
		Shine Trust: Moderate (changed to Medium)
		GAIN (Global Alliance for Improved Nutrition): med (changed to Medium)
		WCIT (Worshipful Company of Information Technologists): Medum (changed to Medium)

**Comment by SanjayLikesCharities** [comment]
Thanks! And sorry about the non-standard confidence levels, I should have cleaned that up before it got to you.
