### ISSUE TITLE
Still unclear what the "References" section is for

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#107]
In the editor, there is a section at the bottom called "references". Still not clear what this is for. I understood it was so that when you state the sources, you can see them all together in one place. However I have tried entering some source documents into the "Data sources" field within each project, and it doesn't appear in the references section (example: http://app.sogive.org/#edit?charityId=rose-road-association)

**Comment by roscoemcinerney** [comment]
The "References" section may have been misbehaving, but there mainly appears to have been a bug in the Data Sources section where you couldn't add a source if one wasn't already present.

This is now fixed, and all reference URLs should now be collected in the References section.
