### ISSUE TITLE
Does the longer description come after the summary description, or replace it?

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#109]
The instructions/help text in the editor for the longer description say:
"A short paragraph, e.g. 2 or 3 sentences. These are used underneath the summary description, so they should add to it and not repeat it."

However, the app appears not to be putting the longer description under the summary description, it appears to be just using the longer description (e.g. http://app.sogive.org/#charity?charityId=rose-road-association)

I think I probably prefer the way the app is doing it, which would require us to change the help text (although we could also go the other way round)

**Comment by roscoemcinerney** [comment]
Ah, that's a simple oversight. I think we should leave the description as it is - I'll update the charity display page later to show the summary followed by the in-depth description.
