### ISSUE TITLE
More images!

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#11]
Let's show more images on the charity pages. Such as nice friendly pictures of the people a charity helps.

NB: part of this may be reviewing the image links in the database for being correct image links.

**Comment by winterstein** [comment]
Let's show an image in the top charity bit.

**Comment by SanjayLikesCharities** [comment]
Next steps for gathering images: discussed on 20/apr between DW and SJ and agreed that we would delay on gathering more images until we have built the data entry tool, which will enable us to gather the images in a better way
