### ISSUE TITLE
Outcomes

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#127]
At the moment, the design for the charity profile page doesn't show outcomes
https://projects.invisionapp.com/d/main#/console/11623296/245857152/preview

Outcomes are actually really important -- it's what everything is all about!

If we find ourselves rushing towards getting something ready for the Kiltwalk, I'm OK with delaying thinking about this for a bit. So I'm logging this issue now to make sure that we don't forget.

**Comment by winterstein** [comment]
Worry not - outcomes are being designed for. Isabel is making designs for various levels of data.
