### ISSUE TITLE
Share by email uses a suboptimal choice of charity name

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#132]
I tried using the email function, and it seems that the subject line is populated with perhaps the official name rather than the display name, although the display name would be the better choice.

Example:
http://test.sogive.org/#charity?charityId=church-of-england-children-s-society
Seems to use "Church of England Children's Society" rather than just "Children's Society"

**Comment by winterstein** [comment]
Fixed on test
