### ISSUE TITLE
Against Malaria Foundation has an issue with the cost per output

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#139]
I checked the AMF editing page, and it said that the calculated cost was £4.11
But I've looked back since, and it was using a cost of £2.09, which I believe is *actually* the calculated cost, contrary to what was stated in the editor.
The cost of £4.11 is the override cost (not the calculated cost) and I have now entered the override cost of £4.11 into the editor and clicked on publish, and it now uses the correct cost.

I'm not sure how the stated calculated cost ended up being different from the actual calculated cost, and whether this could be an issue elsewhere.

http://app.sogive.org/#charity?charityId=against-malaria-foundation

**Comment by SanjayLikesCharities** [comment]
Note also that the override cost field can't be expanded, so we have no way of seeing what's in that cell, which can make it harder to know what's going on.

![image](https://user-images.githubusercontent.com/18592601/30029868-e44d8906-9182-11e7-86fe-7c7f10be63d7.png)

**Comment by winterstein** [comment]
Ah yes, I see the problem. Fixed in latest code (not yet published).

**Comment by SanjayLikesCharities** [comment]
Could there be other charities that have issues?

**Comment by winterstein** [comment]
The bug was a surface one -- that the calculated bit always showed the override (if set). The actual data and calculations were fine.

**Comment by SanjayLikesCharities** [comment]
Does that mean that the override was set? If so, why didn't it feed through to be used in the app?



________________________________
