### ISSUE TITLE
If a search finds nothing - say 0 results

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#14]

**Comment by SanjayLikesCharities** [comment]
Looks good to me

**Comment by SanjayLikesCharities** [comment]
Hmm curious -- recent testing on friends and strangers shows that this issue is back

**Comment by SanjayLikesCharities** [comment]
Have just tested this again, this is still an issue

**Comment by winterstein** [comment]
Confirmed, and fixed.
Also back-ported to the release. But not published yet.

It was a bug in the React plumbing around url parameters that can change.
Copied in some Good-Loop plumbing which handles this more robustly.

 - Daniel

**Comment by SanjayLikesCharities** [comment]
I have tested and found that I still get no feedback when the search finds no results

**Comment by SanjayLikesCharities** [comment]
Oh hang on -- not sure if I'm interpreting @winterstein 's last comment correctly, maybe I shouldn't expect this to be working until the next release?
