### ISSUE TITLE
Login/register when "show all" has been selected

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#142]
Feedback from a friend:
If you click "Show All" at http://app.sogive.org/#search, then open the "login or register" modal and start typing in the email or password field, the whole page slows to an absolute crawl - if I quickly type in my email address, I've got to wait 3 or 4 seconds for the site to recover. I'm 99% sure that this is because the entire charity list is getting rerendered on every keypress (which I can detect because Chrome's Network tab shows it re-parsing the data URIs used for the images of Save The Children and SOS Children's Village every keystroke)

**Comment by winterstein** [comment]
Adding paging should improve this.

Your friend is right -- the whole page gets redrawn for each keypress! Which sounds crazy, but it the normal behaviour when using the React framework.

**Comment by winterstein** [comment]
Closing as subsumed by other task
