### ISSUE TITLE
Missing £ sign is confusing

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#166]
The £ sign is be missing in some cases. I believe those cases are:

- if the charity is a recommended charity
- if there are numbers after the decimal point

In the below example, Malaria Consortium is has a missing £ sign, but Age UK doesn't (Malaria Consortium is recommended, Age UK isn't)
https://app.sogive.org/#search?q=age&from=0

The first thing that users see is the page full of recommended charities, so users are currently not understanding the point of SoGive.

**Comment by winterstein** [comment]
Ah -- comms and our own jargon.
In #157 I wrote "closed in latest code" -- which (to us) means it is fixed in the code, but it has not yet been published. So the issue is still live.

Closing this ticket as a duplicate.
