### ISSUE TITLE
Login not accepted

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#172]
One of the volunteers tried to login and the app refused this. The volunteer wasn't sure why this was rejected, he wasn't sure if he maybe had already registered at some point ages ago. He tried a second time and it worked fine.
![2018-01-06](https://user-images.githubusercontent.com/18592601/34641079-4f60e38a-f2f6-11e7-9122-849585ff11f8.png)

**Comment by winterstein** [comment]
Looking at the logs... They say he tried to login. The server didn't recognise his email. Then he signed up  and it worked. ie it looks normal and correct.

NB: I will add extra logging to keep more details for future.

**Comment by SanjayLikesCharities** [comment]
I didn't see what he did all the way through, but based on what you say, I guess he probably tried to register by filling in the form (like I've done here in this screenshot) and then pressing Register and expected to be registered. Then when he wasn't registered it looked like a bug to him.

So perhaps it's not an bug per se and more of a UX issue?

![image](https://user-images.githubusercontent.com/18592601/34671736-92fdb716-f473-11e7-8971-6e1eb90d31da.png)
