### ISSUE TITLE
Logos entirely absent in some cases

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#18]
For (eg) Downs Syndrome Association, Hope & homes, Salvation Army and a few others, there is no logo shown at all (not even a placeholder) even though the original spreadsheet includes a link. I believe this is different from "Logos not displaying #5", but not 100% sure

**Comment by winterstein** [comment]
Looking at Salvation Army, the logo entry is blank in the .csv snapshot used when we published the app. 

@SanjayLikesCharities Maybe you added it to the spreadsheet in the last week?
