### ISSUE TITLE
Absent data

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#182]
There are some instances where data was populated for a charity, but that data is no longer there. Here are some instances where I have kept enough records to be able to tell that this is what's happened:

![image](https://user-images.githubusercontent.com/18592601/41032971-d59a77ac-697c-11e8-8d17-7e5dc225a2c9.png)

(Same table again in case you want to copy and paste)
Charity | Date of do-a-thon | Unit cost
-- | -- | --
https://app.sogive.org/#edit?charityId=royal-blind | 6-Jan-18 | £54,000
https://app.sogive.org/#edit?charityId=mary-s-meals | 6-Jan-18 | £14

**Comment by winterstein** [comment]
I consider this serious. But unfortunately we don't have a way to do low-level investigations more than a few weeks back.
