### ISSUE TITLE
Markdown in stories & descriptions. Carriage returns not rendered in the qualitative / stories bit

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#19]
for example, Give Directly's info isn't comprehensible

**Comment by SanjayLikesCharities** [comment]
Not sure if this should be a separate issue in its own right (?) but a related note is that apostrophes are currently sometimes being rendered as a space character. See (eg) project Mala

**Comment by winterstein** [comment]
The 's is probably fixed -- it was probably non-standard apostrophe characters

**Comment by DanielRobertAppel** [comment]
Looks good to me
