### ISSUE TITLE
KickStarter: an FAQ setting out what the KickStarter is funding + relationship to app

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#25]

**Comment by SanjayLikesCharities** [comment]
Draft is here: https://docs.google.com/document/d/1W3AszYWXxtnKB3kk1Qn1ECmzT3mSebxek8lvJUkkX8Q/edit

**Comment by SanjayLikesCharities** [comment]
What is the kickstater funding? web development, stretch goals - data entry app, more anlaytical staff, other fun stuff

**Comment by SanjayLikesCharities** [comment]
@winterstein I think we discussed this (sorry), but I'm not sure why we need this? There is plenty on the kickstarter page itself to set out what the kickstarter is funding. And as for relationship to the existing app, this is only visible to those who have the app.sogive.org url, which is a limited inner circle of people who are close to the project, and will understand that more work is needed. What we do need, however, is something on the website to indicate that the kickstarter is live and invite people to view it. I'll send an email about this.

**Comment by winterstein** [comment]
Explaining it in an email to the inner circle would work.

I think we need something short and simple to avoid confusing (and possibly
alienating) the inner circle. If you know there is an app, then it's not
clear what the KickStarter is funding. And this is a group who care about
transparency and accountability.

 - Daniel
