### ISSUE TITLE
Order in which charities appear in search results has no apparent rhyme or reason

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#30]
Could change to (eg) alphabetical (but maintaining the requirement that "Analysis in Progress" charities come at the end)

**Comment by winterstein** [comment]
Alphabetical.

**Comment by SanjayLikesCharities** [comment]
Presumably the testme label is requesting testing in the test environment? Just tried testing this in the live environment and it doesn't appear to be alphabetical

**Comment by winterstein** [comment]
@SanjayLikesCharities - Yes. I put testme on when I think the code is ready. But it doesn't reach the test or live server until @DanielRobertAppel does a publish.

**Comment by DanielRobertAppel** [comment]
Latest code looks good on latest local test.  I think that it's ready to be live.

**Comment by DanielRobertAppel** [comment]
Actually, I take that back.  Search results are out-of-order

**Comment by DanielRobertAppel** [comment]
@winterstein

**Comment by SanjayLikesCharities** [comment]
Have just tested this - agree that search results appear to be out of order

**Comment by DanielRobertAppel** [comment]
I think that the fix will be something simple.

I believe that the ES query is asking for items by "name", descending.  But I also believe that there are multiple child-objects that have "name" for their value. 

Let me take a crack at debugging the query.

**Comment by DanielRobertAppel** [comment]
Update:  DW and I have found a fix for the internal query.  Implementing soon....

**Comment by DanielRobertAppel** [comment]
Update:  New code implemented.  Server Updated.  Results are now alphabetical.
