### ISSUE TITLE
Some charities shouldn't be shown as donation recipients

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#32]
We currently accept donations for all charities in the database. However there are some charities which don't accept donations from the public (e.g. Goldman Sachs Gives) but which might still be in the database.

Required actions: Sanjay to add column to the database to indicate whether a charity accepts donations from the public, then we update the SoGive web app accordingly (perhaps by simply not showing them in the search results)

**Comment by winterstein** [comment]
Front end code written - expects noPublicDonations in the database.

**Comment by winterstein** [comment]
@SanjayLikesCharities Could you create a noPublicDonations column and fill in the data? Thanks.

If this slips past March - I think it's not a big deal. As long as these charities don't have impact info, they're unlikely to receive donations.

**Comment by SanjayLikesCharities** [comment]
Column added (it's column D in the spreadsheet at the moment). I have fully populated it.

**Comment by winterstein** [comment]
Closed http://local.sogive.org/#charity?charityId=goldman-sachs-gives
