### ISSUE TITLE
Searching for acronyms doesn't always find the charity

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#37]
Solution: Sanjay to add in more acronyms as alternative names for charities

**Comment by winterstein** [comment]
Hello @SanjayLikesCharities - Where would you enter alternative names?

How about a column "alternative names", and comma separated within that?

**Comment by SanjayLikesCharities** [comment]
Have just gone through and added in some more acronyms to address the immediate problems.
Alternative names column is also a possibility. I have resisted adding this so far because there are so many columns in the database, and each time we add another it just makes it more difficult for volunteers to navigate their way around.

**Comment by winterstein** [comment]
Fix more as we find them
