### ISSUE TITLE
Gift aid functionality not always provided when it should be

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#38]
Example: Schistosomiasis Control Initiative (aka SCI)
In the spreadsheet the "UK-based charity?" column is (and for a long time has been) populated with a "yes", but no gift aid check box is shown. Similarly for Halo Trust

Others (eg Shelter or Hope and Homes) seem to work just fine

I tried to find examples where the error was the other way (i.e. it's not a gift-aidable charity, but the check box was shown anyway) I didn't find an example of this error

**Comment by winterstein** [comment]
Most likely the spreadsheet was edited after we took the download. Action: Test when releasing.

**Comment by SanjayLikesCharities** [comment]
code was referring to thecharity reg no (not the "uk reg charity" column. make suer that the reg no oclumn is filled in, even for odd cases like sci

**Comment by SanjayLikesCharities** [comment]
Earlier SCI was the only charity which really needed to have a charity registration number to indicate that it's giftaidable but didn't have one. I have since contacted SCI and got hold of one, so that's now been populated in the spreadsheet

**Comment by SanjayLikesCharities** [comment]
Have just received another note from SCI - they made a mistake, and in fact there is no charity registration number for SCI:
- SCI isn't a separate charity in its own right, it's part of Imperial College
- Imperial College doesn't have a registration number because the Charities Act 2006 allows for some charities to be "exempt charities" (i.e. they don't have to register)
- It does have an HMRC reference number, however this isn't the same as a charity commission reference number
- this new information about how Gift Aid functions indicates the problems with using the existence of Charity Commission registration number as the basis for deciding whether something is gift-aid-able.

**Comment by winterstein** [comment]
Desired fix: Change "uk based" column to "gift aid", and use that.

**Comment by SanjayLikesCharities** [comment]
I have updated the column heading in the spreadsheet
