### ISSUE TITLE
If the user already has a stripe account, the UX is confusing

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#41]
If there is already a stripe account for the user, when the payment process requests the email address, it will say "Enter the verification code to use the payment info you stored with Stripe". This can be confusing at first - so need to have something to explain that this is happening because it's recognised that the user has a stripe account

**Comment by winterstein** [comment]
This is how Stripe does it. They are experts in this, and let's leave it to them.
