### ISSUE TITLE
Explanation needed of rationale for just showing one project

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#43]
People might want to see "£x donated would fund a school assemblies, b counselling sessions, c macguffins". Need to add in explanation for why we show just one.

Actions: Sanjay to write explanation
Someone else to add in link to this explanation for multiproject charities. Also need way of indicating which ones are multiproject charities

**Comment by winterstein** [comment]
Add to FAQs

**Comment by SanjayLikesCharities** [comment]
This is in the FAQs now
