### ISSUE TITLE
Need to indicate to users that we have very low confidence in some of the numbers

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#48]
In some cases - especially where the data available is sparse or has been shoehorned into the database, we have lower confidence in the quality of the figure. There is a column (currently column AX) in the spreadsheet which indicates how confident we are about the figures. 

Need a way to communicate this. Could be one for our design experts (Corrado and Elena) to also think about.

**Comment by SanjayLikesCharities** [comment]
I mentioned above that "There is a column (currently column AX) in the spreadsheet which indicates how confident we are about the figures." Those columns are labelled "confidence indicator" and "comments on confidence indicator". Would be good to add some sort of indicator to the SoGive app so that our users know about this

**Comment by winterstein** [comment]
Duplicate?
