### ISSUE TITLE
Which charities are and aren't finished

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#54]
When I view the charities which are marked as analysed (or rather *not* marked as analysis in progress) there are fewer of them than there are in the spreadsheet.

Here are a few examples of charities which are marked as finished in the spreadsheet but not marked as such in the app:

Artbox London
Camfed
Prince's Trust

**Comment by winterstein** [comment]
Let's see:

Artbox London: http://app.sogive.org/#search?q=artbox marked as in progress

Data: http://app.sogive.org/charity/artbox-london -- this does not have a
ready flag

In the spreadsheet --
https://docs.google.com/spreadsheets/d/1Gy4sZv_WZRQzdfwVH0e3tBvyBnuEJnhSFx7_7BHLSDI/edit#gid=0
This is marked as ready.

However in the data snapshot 9charities.csv) -- it is marked as not ready.

It looks like this was edited after the snapshot was taken.
Next time we update the data, it will get the latest state.

I'm going to guess the other cases are the same.

 - Daniel


---------- Forwarded message ----------
