### ISSUE TITLE
Data editor: need a charity number for OSCR as well as E&W Charity Comm

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#66]
Currently have a field for the E&W charity commission number. I don't think there's a field for OSCR number as well - should add this. This is not a mega urgent requirement

Lower priority, but over time we may also need:
NI Charity Commission number
registration number with the IRS for US charities
CIC number
Companies house reg number (for relevant social enterprises)

**Comment by winterstein** [comment]
Added OSCR, NI, US reg, companies house.

What's a CIC number?
