### ISSUE TITLE
Editor: year start/end apparent discrepancy

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#71]
From Shivani:
For Windows system, there is a discrepancy in the selected and displayed option. For example, if a date such as 1st May is selected, the displayed date shows 1st April, so 1 month behind. This means certain dates cannot be selected (Especially 31st of many months).  Example: if we wanted to enter the date 31st March (which is a very commonly-needed date) we would have to enter 31st April. Unfortunately this date doesn't exist, so we can't enter this! Manual entering of dates doesn't work, as it just randomly enters values.

**Comment by winterstein** [comment]
I am unable to reproduce this exact bug, but I did see some odd behaviour
with the date editor.

So I have turned it into a simple text entry box.

NB: this is in latest code, but it has not been published to a server.
