### ISSUE TITLE
Editor has "mirroring" problem with impact units, stopping us from having more than one impact per project

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#79]
Text field for impact units is often linked to the 'add impact units' box in the project section. As a result, unable to capture multiple impacts with different names.

More detail:

In the below example, I entered the text "disabled leisure centre customers" into the field on the upper left. Then I entered the number -- so far so good.

![image](https://user-images.githubusercontent.com/18592601/27384459-de5bc47c-5686-11e7-96c9-5cda0af63cc5.png)

Then I tried to enter a new impact -- "total leisure centre customers". I started entering the impact unit into the lower field, and as soon as I did so the words that I was typing into the lower field were also automatically appearing in the upper impact unit field, overtyping what was there before. The words in the upper left field were mirroring what was in the lower field that I was typing into.

![image](https://user-images.githubusercontent.com/18592601/27384618-7146cfc0-5687-11e7-926b-a6be2d6fa7cf.png)

**Comment by winterstein** [comment]
That was a fun bug. Shared sub structure between objects, coming from set-null being a no-op within the state update code. All fixed.
