### ISSUE TITLE
KickStarter campaign links?

### ISSUE THREAD

**Issue by winterstein** [winterstein/sogive-app#8]
Will the kickstarter campaign link to the app?

Will the app link to the campaign?

**Comment by SanjayLikesCharities** [comment]
I'm not expecting the crowdfunding campaign to link to the app - but it will link to the website http://sogive.org

**Comment by winterstein** [comment]
I agree. i think we should have an FAQ which sets out how the KickStarter relates to the app, so that people understand what they are funding. 

The risk would be that people will naturally think they're funding development of the initial app. Then they find out we've already built an alpha version, and they feel sort of cheated.

I'm not sure how to position just what the kickstarter is funding.
There's lot of dev and graphic design work to be done.
There's the data-entry app. 
There's the data-entry work.
Then there are marketing costs to promote the app.
And running costs (servers & maintenance).

Perhaps running costs (servers and maintenance) for the first year?
