### ISSUE TITLE
Editor: publishing seems temperamental (might be a minor issue?)

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#80]
Someone who hadn't been given publishing rights was able to publish things to the front end - it worked sometimes, didn't work at other times.

It may not be a serious problem in that I don't anticipate people trying to hack into our database, so if someone is able to publish despite not having the publishing rights, this might be fine.

Conversely, if someone who did have publishing rights found that they couldn't publish, this would be a problem (but this hasn't been adequately tested)

Background info:
On https://app.sogive.org/#editordashboard
it says:
"Use this form to add someone to the editors team. Anyone can make edits, but only approved editors can publish them." When I talk about being given publishing rights in this post, I'm referring to not being an "approved editor"

**Comment by winterstein** [comment]
Hello,

The security is a work-in-progress. It's not enforced.
I think this is a safe corner to cut for now, as we're unlikely to be
attacked.

 - Daniel

**Comment by winterstein** [comment]
We have another issue about editor rights, so closing as a duplicate.
