### ISSUE TITLE
Units not always captured correctly

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#86]
Example: macmillan cancer support
https://app.sogive.org/#charity?charityId=macmillan-cancer-support
SoGive is (correctly) picking up data from the most recent year for which data is available (2015)
The units used by the app are "People (singular: person) supported"
However this is not the right wording. The wording should be "people (singular: person) reached and supported"; this can be seen in the spreadsheet. It appears that the app has picked up the units from the wrong row of the spreadsheet (i.e. a row that is not consistent with the figures)

The wording is carefully chosen to align with the figures -- in the case of Macmillan, it would be wrong to say "people supported". To suggest that these users have been supported is overegging it, and we are misleading our users by suggesting that they have.

**Comment by winterstein** [comment]
Sounds like a data versioning / update issue. Should go away with a clean update of everything.

**Comment by SanjayLikesCharities** [comment]
Agreed. Since posting this I've realised that since we didn't do a June release we're still using the late May data. Looking at the archived data suggests that the app is in fact behaving as expected.
