### ISSUE TITLE
Representative project not always correctly picked up

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#88]
Example: RNLI
https://app.sogive.org/#charity?charityId=royal-national-lifeboat-institution-rnli

The inputs and outputs shown relate to the "overall" row in the spreadsheet. However that row is not marked as representative for this charity. The representative row is marked as the lifeboat crews project. The units used (launches of lifeboats) does look correct - it relates to the row marked as representative.

**Comment by winterstein** [comment]
Looks like we fixed this.
