### ISSUE TITLE
Adhoc adjustments appear not to be applying

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#90]
The rule is that where the calculation approach departs from the standard approach, the spreadsheet should have some content populated in the "adhoc adjustments" column.

The code should then pick up the figure calculated in the spreadsheet and use this, and should also include the text from the adhoc adjustments column.

Examples:
Give directly is an important charity; it's not working correctly: https://app.sogive.org/#charity?charityId=give-directly
WaterAid: https://app.sogive.org/#charity?charityId=wateraid
Duy der isn't a very high profile charity, but an example where this isn't working: https://app.sogive.org/#charity?charityId=duy-der
Women for women seems to hvae the right number, but that's by coincidence I think, and the explanatory text isn't there. https://app.sogive.org/#charity?charityId=women-for-women-international

Every charity I have tested for this doesn't seem to be implementing this at all.

Flagged as important because the app is giving incorrect info as a result of this.

**Comment by SanjayLikesCharities** [comment]
Plan is to update editor to be able to accommodate adhoc adjustments, and then manually put the adhoc adjustments into the editor

**Comment by winterstein** [comment]
Testing now:
Give Directly works.
But Water Aid is not showing impact
https://app.sogive.org/#charity?charityId=wateraid

**Comment by SanjayLikesCharities** [comment]
I just tried adding in the adhoc adjustment to the unit cost for WaterAid, and then I clicked on publish. There was no reassuring response from the site to indicate that the publish had worked, however this is normal -- I assume it did publish. The cost used in the app had not updated

**Comment by winterstein** [comment]
Hello Sanjay
I think this is a bug report, though I'm not 100% sure. Could you provide
more details?
What specifically was entered?
What specifically is wrong?
Also, please give the url with bug reports.
Thanks,
 - Daniel

**Comment by SanjayLikesCharities** [comment]
Similarly for Project Healthy Children,
http://app.sogive.org/#charity?charityId=project-healthy-children

Interestingly, when I did it for several others, it seems to have worked fine:
http://app.sogive.org/#charity?charityId=schistosomiasis-control-initiative-aka-sci
http://app.sogive.org/#charity?charityId=friends-of-the-children-of-orissa-foco
http://app.sogive.org/#charity?charityId=malaria-consortium

**Comment by SanjayLikesCharities** [comment]
Just seen your request for more info:

For Project Healthy Children, I entered the override unit cost of £0.05 into the field which we have variously called the adhoc adjustment or override.

The thing that is wrong is that the cost in the app is not updated to be £0.05. When I talk about the cost in the app, I mean when I go to app.sogive.org and search for Project healthy children, I don't see the cost reflecting the number I entered. When I look in the profile page of the charity, I similarly don't see this.

For WaterAid, I similarly don't see the numbers that I expected, although I suppose this might be because it's rounding more aggressively than I remembered.

**Comment by SanjayLikesCharities** [comment]
Pardada Pardadi, like Project Healthy Children, doesn't seem to be applying the adhoc adjustment / override. A unit cost of £300 was entered into the override field, however the profile page doesn't show this

http://app.sogive.org/#charity?charityId=pardada-pardadi

**Comment by SanjayLikesCharities** [comment]
Looking back at this, I see that the WaterAid case was likely just because of rounding. This makes me wonder whether we should be careful about the rounding approach for charities where we take the unit cost from the charity. I didn't recognise the unit cost that we showed for WaterAid in SoGive (£20) as being the same as the £15 unit cost provided by WaterAid, and if others saw it, they might not either. This might leave us in the awkward position of having to explain why we take a different view.

**Comment by winterstein** [comment]
OK

Pardada-Pardadi is due to the ready flag not being set. At some point we moved from ready being per-project to per-charity. Some of the code is still checking at the project level. That's fixed in latest code.

WaterAid is rounding (good diagnosis!). Moving from "N people x £10 = X" to unit-cost as our standard phrasing should fix this issue.
