### ISSUE TITLE
Tags not being used in search

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#91]
The data gathering process involves assigning a number of tags. These are intended to be used in the search process (it may have other applications too, in the future)

At time of writing, the search function ignores the tags. 
Currently the tags are classified -- there is no need for the search to do anything funny and treat those different types of tag in different ways. Simply include the tags within the list of things that the search function looks.

**Comment by winterstein** [comment]
Hm - I can't reproduce this in latest code.
Testing
http://local.sogive.org/#search?q=health
returns the AMF (which has tag health, but doesn't otherwise mention health).

Do you have an example showing the problem?
