### ISSUE TITLE
Importer: Description and Summary Description are confused

### ISSUE THREAD

**Issue by roscoemcinerney** [winterstein/sogive-app#95]
SoGive's interface has "Summary Description" and "Description"
The spreadsheet has "Description" and "Long Description"
This means that currently, "Description" (the short one) from the spreadsheet gets put into "Description" (which should contain the long description) in the system.

@SanjayLikesCharities I've made the importer recognise "Summary Description" and "Description" as fields in the CSV, and I've edited the Google Docs spreadsheet to match this convention, so going forward the right fields should be imported to the right place.

I decided which names to use fairly arbitrarily - let me know if you'd prefer I standardised on different ones.

**Comment by SanjayLikesCharities** [comment]
Agreed that this is a source of potential confusion. I think that just calling it "ddescription " could lead to confusion as to which description it is. May I suggest that we use "summary description " and "longer description "?

If you would like me to change the spreadsheet to reflect this, let me know

**Comment by roscoemcinerney** [comment]
"Summary description" and "longer description" will be fine, I have the importer reading those fields now.

**Comment by SanjayLikesCharities** [comment]
Cool. Does that mean I should update the spreadsheet (and by extension the CSV) to say "summary description" and "longer description"?

**Comment by roscoemcinerney** [comment]
I think I changed it in the Google sheet, but if it needs to be changed elsewhere as well, please do.
