### ISSUE TITLE
Several charities missing the impact data in app

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#97]
Several charities include impact data in the CSV/spreadsheet, however in the app the data is not shown.

Examples: Age UK, Action for Children, Brooke, Clic Sargent, Climate Outreach Information Network, etc

**Comment by SanjayLikesCharities** [comment]
It looks like the charities where this occur are the charities where the charity landing page says "old projects"
Examples: the following say "old projects" and have no impact data:
http://app.sogive.org/#charity?charityId=age-uk
http://app.sogive.org/#charity?charityId=action-for-children
http://app.sogive.org/#charity?charityId=children-s-society
The following don't say "old projects" and do have impact data:
http://app.sogive.org/#charity?charityId=against-malaria-foundation
http://app.sogive.org/#charity?charityId=anthony-nolan-trust
http://app.sogive.org/#charity?charityId=alzheimer-s-society
So far, for the charities marked as finished, I've found that saying "old projects" occurs if and only if there is no impact data (I haven't yet seen a counterexample to this rule)

**Comment by winterstein** [comment]
I checked the examples -- they seem to be working now.
