### ISSUE TITLE
For several charities, impact units are missing

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#98]
In these examples, the impact units are populated in the CSV/spreadsheet, but somehow missing in the app

Examples: Core arts, Dogs trust, Islamic Relief, MHA (aka Methodist Homes), St Mungo's

**Comment by SanjayLikesCharities** [comment]
Not sure if this is linked to issue #97

**Comment by winterstein** [comment]
Checked Islamic Relief
http://app.sogive.org/#charity?charityId=islamic-relief-worldwide
£10 = 1 sustainable livelihood
