### ISSUE TITLE
Some charities duplicated

### ISSUE THREAD

**Issue by SanjayLikesCharities** [winterstein/sogive-app#99]
The app includes the following as separate entities, despite the fact that the CSV/spreadsheet doesn't have this sort of duplication.

EMPOWER - THE EMERGING MARKETS FOUNDATION
EMPOWER EMERGING MARKETS FOUNDATION
Great Ormond Street Hospital
Great Ormond Street Hospital Children's Charity
PDSA
PDSA (People's Dispensary for Sick Animals)
Sightsavers
Sightsavers (Royal Commonwealth Society for the Blind)

**Comment by winterstein** [comment]
At a guess: the names were changed in the spreadsheet. So the data importer
created new records.

I suggest we

1. Drop the ES /charity database.
2. Rebuild it from a fresh .csv snapshot of the spreadsheet.
@Dan A - Could you do that?
Thanks.

3. Then Sanjay & the Volunteers switch to making edits in the Editor.

 - Daniel

**Comment by winterstein** [comment]
@DW

done.

On 1 August 2017 at 10:43, Daniel Winterstein <daniel.winterstein@gmail.com>
wrote:

> At a guess: the names were changed in the spreadsheet. So the data
> importer created new records.
>
> I suggest we
>
> 1. Drop the ES /charity database.
> 2. Rebuild it from a fresh .csv snapshot of the spreadsheet.
> @Dan A - Could you do that?
> Thanks.
>
> 3. Then Sanjay & the Volunteers switch to making edits in the Editor.
>
>  - Daniel
>



-- 
Daniel Appel
Systems Administrator
Winterwell Associate / SoDash


127 Rose Street South Lane, Edinburgh, EH2 4BB, United Kingdom

www.sodash.com
Part of winterwell.com

**Comment by winterstein** [comment]
Dan A reports he has done this.
